#!/bin/bash
# @see https://stackoverflow.com/questions/18884992/how-do-i-assign-ls-to-an-array-in-linux-bash

SCRIPT_PATH=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)

PATH_TO_COMPIFY=$SCRIPT_PATH'/../bin/compify.phar'

shopt -s nullglob
array=(*/)
shopt -u nullglob

for entry in ${array[@]}; do
    if [ -d "$entry/.git" ]; then
        echo "$entry"
        cd "$entry"
        git pull
        git fetch origin
        if [ -d "entry/vendor" ]; then
            php $PATH_TO_COMPIFY crush
        fi
        cd ..
    fi
done;
